// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniSys.Data;

#nullable disable

namespace UniSys.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617115546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentSubject", b =>
                {
                    b.Property<int>("EnrolledSubjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("EnrolledSubjectsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("UniSys.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("GPA")
                        .HasColumnType("double precision");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniSys.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditHours")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("TutorId")
                        .HasColumnType("integer");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UniSys.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<int?>("UniversityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("UniSys.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("StudentSubject", b =>
                {
                    b.HasOne("UniSys.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("EnrolledSubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniSys.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniSys.Models.Student", b =>
                {
                    b.HasOne("UniSys.Models.University", null)
                        .WithMany("Students")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("UniSys.Models.Subject", b =>
                {
                    b.HasOne("UniSys.Models.Tutor", "Tutor")
                        .WithMany("TeachingSubjects")
                        .HasForeignKey("TutorId");

                    b.HasOne("UniSys.Models.University", null)
                        .WithMany("Subjects")
                        .HasForeignKey("UniversityId");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UniSys.Models.Tutor", b =>
                {
                    b.HasOne("UniSys.Models.University", null)
                        .WithMany("Tutors")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("UniSys.Models.Tutor", b =>
                {
                    b.Navigation("TeachingSubjects");
                });

            modelBuilder.Entity("UniSys.Models.University", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");

                    b.Navigation("Tutors");
                });
#pragma warning restore 612, 618
        }
    }
}
